### ISSUE TITLE
Download page repo QR code doesn't match what I see in F-Droid

### ISSUE THREAD

**Issue by andrewguertin** [microg/microg.org#3]
When adding the microG F-Droid repo to my phone I noticed that the QR code given on the page doesn't match what I see in F-Droid, even though the fingerprint matches.

Eventually I figured out that the QR code generated by F-Droid represents a URL in all uppercase, while the QR code on the website represents the same URL in all lowercase.

**Comment by andrewguertin** [comment]
This affects the download page and the fdroid page on the website, as well as some of the wiki pages for various github projects.

**Comment by landry314** [comment]
I went through the same thing today and also figured out it was due to the difference between all upper or lower case in the URL. You seemed to have been ignored on this issue which is strange because this is actually a security verification issue. Yes, the written out hexadecimal can be entered in f-droid and compared visually to match but if the QR images are compared visually then they are different. I spent about 30 minutes trying to figure this out. I felt like when you are comparing a fingerprint the QR code connected to that fingerprint needs to be the same. Am I crazy here?

f-droid generates the QR image from the fingerprint in the repository section in the f-droid app as all UPPER CASE like this:

https://microg.org/fdroid/repo?fingerprint=9BD06727E62796C0130EB6DAB39B73157451582CBD138E86C468ACC395D14165

but on your f-droid web page here:

https://microg.org/fdroid.html

the QR image is generated from:

https://microg.org/fdroid/repo?fingerprint=9bd06727e62796c0130eb6dab39b73157451582cbd138e86c468acc395d14165

and hence is different. I suggest you also generate your image to match f-droid's format to eliminate this confusion.
